# Generated by Django 5.2.4 on 2025-08-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_othermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherModel',
        ),
    ]
