# Generated by Django 5.2.4 on 2025-08-13 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_views', '0004_othermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='email',
            field=models.CharField(default='example@example.com', validators=[django.core.validators.EmailValidator]),
        ),
    ]
