# Generated by Django 5.2.4 on 2025-08-13 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_views', '0005_examplemodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='email',
            field=models.CharField(default='example@example.com', validators=[django.core.validators.EmailValidator()]),
        ),
    ]
